# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('description', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('company_logo', models.URLField()),
                ('company', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('company_url', models.URLField()),
                ('how_to_apply', models.TextField()),
                ('location', models.TextField()),
                ('type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
