# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-30 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200830_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='company',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='company_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='created_at',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='how_to_apply',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='companydetails',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
